sellticket: main.c
	gcc -o sellticket main.c
run1:sellticket
	./sellticket input1.txt output.txt
run2:sellticket
	./sellticket input2.txt output.txt
run3:sellticket
	./sellticket input3.txt	output.txt
run4:sellticket
	./sellticket input4.txt	output.txt
run5:sellticket
	./sellticket input5.txt	output.txt
run6:sellticket
	valgrind --leak-check=full ./sellticket input1.txt output.txt
